- src/components/common/button/Button.stories.tsx
- src/components/common/button/Button.styles.ts
- src/components/common/button/Button.tsx
**공통 버튼 컴포넌트 추가**
작업 내용
- 버튼 구성
텍스트만 있는 버튼
아이콘 + 텍스트가 함께 있는 버튼
- 스타일
fill : 버튼에 배경색이 채워진 형태
outline : 버튼에 테두리만 있는 형태
- 사이즈 구분
small, medium, large 세 가지 크기 옵션
> design: 공통 버튼 컴포넌트 추가

- package.json
- src/components/common/CustomSelect/CustomSelect.stories.tsx
- src/components/common/CustomSelect/CustomSelect.styles.ts
- src/components/common/CustomSelect/CustomSelect.tsx
- src/constants/RecruitmentCapacity.ts
- src/constants/options.ts
- src/types/types.ts
- src/utils/optionUtils.ts
- 'react-select' 라이브러리 추가
- 'option.ts' 파일로 'react-select' 형식에 맞게 값 변환
- 'RecruitmentCapacity.ts' 상수 추가
- 상수 변환 유틸 추가
> feat: 셀렉트 컴포넌트 추가

- src/components/common/CustomSelect/CustomSelect.stories.tsx
- src/components/common/CustomSelect/CustomSelect.tsx
> style: JSDoc 주석 추가

- src/components/common/CustomSelect/CustomSelect.stories.tsx
- src/components/common/CustomSelect/CustomSelect.styles.ts
- src/components/common/CustomSelect/CustomSelect.tsx
> feat: 카테고리 셀렉트 추가

- .storybook/preview.ts
- src/index.css
desgin: box-sizing 옵션 border-box로 수정하였습니다.
storybook의 preview.ts 에  index.css import 하도록 변경하였습니다.
> desgin: box-sizing 옵션 border-box로 수정

- src/components/common/TextArea/TextArea.stories.tsx
- src/components/common/TextArea/TextArea.styles.ts
- src/components/common/TextArea/TextArea.tsx
- src/components/common/input/Input.stories.tsx
- src/components/common/input/Input.styles.ts
- src/components/common/input/Input.tsx
인풋 컴포넌트와 텍스트 박스 컴포넌트 추가하였습니다!
자꾸 스타일을 하나씩 빼먹어서 불필요한 커밋이 생겼습니다..
> feat: Input 컴포넌트, TextArea 컴포넌트 추가

- src/components/features/profileDropdown/MenuItem/MenuItem.stories.tsx
- src/components/features/profileDropdown/MenuItem/MenuItem.styled.ts
- src/components/features/profileDropdown/MenuItem/MenuItem.tsx
- src/components/features/profileDropdown/ProfileDropdown.stories.tsx
- src/components/features/profileDropdown/ProfileDropdown.styled.ts
- src/components/features/profileDropdown/ProfileDropdown.tsx
- src/components/layout/Header/Header.tsx
- src/index.css
- ProfileDropdown 컴포넌트와 내부의 MenuItem 컴포넌트 구현
(파일 이름 이상한거 있는지 확인해주시면 감사하겠습니다.)
> feat: PofileDropdown 컴포넌트 구현

- package.json
- src/components/common/TextEditor/TextEditor.stories.tsx
- src/components/common/TextEditor/TextEditor.styles.ts
- src/components/common/TextEditor/TextEditor.tsx
- src/components/common/Title/Title.stories.tsx
- src/components/common/Title/Title.styles.ts
- src/components/common/Title/Title.tsx
- src/constants/Title.ts
- 작성 에디터 react-quill 라이브러리 추가
- Title.ts 상수 추가
> feat: TextEditor, Title 컴포넌트 추가

- src/components/common/card/Card.style.ts
- src/components/common/card/CardContainer.style.ts
- src/css/common.css
- 메인화면 max-width 값 변경 및 카드컴포넌트 스타일 조정
- 기존 1600px → 노트북 화면을 고려하여 1200px
> fix: 메인화면 max-width 값 변경 및 카드컴포넌트 스타일 조정

- src/css/common.css
- src/pages/RootLayout.tsx
- 헤더영역 position 스타일 변경으로 인한 화면 오류 수정
> fix: 헤더영역 position 스타일 변경으로 인한 화면 오류 수정

- src/components/common/CustomSelect/CustomSelect.styles.ts
- src/components/common/Pagination/Pagination.styles.ts
- src/components/common/SearchBar/SearchBar.styled.ts
- src/components/common/writeButton/WriteButton.styles.ts
- src/pages/MainPage/MainPage.styles.ts
- 폰트 크기 통일
- 검색바 placeholder 글자 잘리지않게 width 수정
- 페이지네이션 active 스타일 수정
- 글작성 버튼 크기 조정
> fix: 메인화면 스타일 수정

- src/components/features/login/LoginModal.tsx
> fix: 로그인모달 styled props 오류 수정

- src/components/features/Main/MainBanner/MainBanner.styles.ts
- src/components/features/Main/MainBanner/MainBanner.tsx
- src/css/common.css
- src/hooks/useAuthApi.ts
- main페이지 배너에 애니메이션을 추가했습니다..!
: 버튼의 무빙과... Meetify의 애니메이션 정도..?
- JWT 토큰과 닉네임을 전역 상태에 설정
: 토큰 값을 헤더에 넣어서 활용하는 작업은 좀 더 공부해보고 마저 진행하고, 닉네임은 전역에 설정해뒀습니다 !
> Style: main banner 애니메이션 적용 및 전역 닉네임 설정

- src/components/common/LoadingSpinner/LoadingSpinner.stoires.tsx
- src/components/common/LoadingSpinner/LoadingSpinner.styled.ts
- src/components/common/LoadingSpinner/LoadingSpinner.tsx
- src/components/features/Main/MainBanner/MainBanner.styles.ts
- src/pages/ErrorPage/ErrorPage.tsx
- src/pages/ErrorPage/Errorpage.styles.ts
**1. Loading spinner 컴포넌트 추가**
: 어느 페이지에 로딩스피너가 필요한지 몰라서 일단 만들어뒀습니다. 
필요한 부분에 사용하시면 될 것 같아요 !
**2. error page 제작 완료**
> Style: loading spinner / 404 error page 추가

- src/components/common/icon/ListIcon/ListIcon.stories.ts
- src/components/common/icon/ListIcon/ListIcon.tsx
- src/components/features/Chat/ChatRoom/ChatRoom.styles.tsx
- src/pages/ChatsPage/ChatsPage.style.tsx
- src/pages/ChatsPage/ChatsPage.tsx
> degisn: 채팅창 반응형 기본 디자인 추가

- src/components/features/Chat/ChatDay/ChatDay.styles.ts
- src/components/features/Chat/ChatRoom/ChatRoom.styles.tsx
- src/components/features/Chat/ChatRoom/ChatRoom.tsx
- src/components/features/Chat/ChatRoomInfo/ChatRoomInfo.styles.ts
- src/components/features/Chat/ChatRoomInfoContainer/ChatRoomInfoContainer.styles.tsx
- src/components/layout/Header/Header.tsx
- src/css/common.css
- src/pages/ChatsPage/ChatsPage.style.tsx
- src/pages/RootLayout.tsx
채팅 페이지 디자인 1차 수정했습니다.
카톡 같은 느낌을 살려서 적용했습니다.
> design: 채팅 페이지 디자인 1차 수정

- .env
- src/components/features/login/Input.tsx
- src/components/features/login/LoginModal.styles.ts
- src/hooks/useAuthApi.ts
- src/services/userProfile/fetchUserProfile.ts
- src/services/userProfile/saveUserProfile.ts
.env 파일에
VITE_API_URL=https://meetify-be.vercel.app/api 이렇게 설정하신 뒤
서버 통신하는 파일에
const VITE_API_URL = import.meta.env.VITE_API_URL;
이 라인 추가해서 사용하시면 되시겠습니다.
ex)
axios.patch(`${VITE_API_URL}/user-profile`
> chore: 서버 URL 환경변수 사용하도록 수정

- package.json
- src/components/features/login/LoginModal.styles.ts
- src/components/features/login/LoginModal.tsx
- src/components/features/register/ProfileProposal.tsx
- src/components/features/register/RegisterModal.tsx
- src/pages/MyInfoPage/MyInfoPage/MyInfoPage.tsx
**- 회원 탈퇴 시 로그아웃 상태 적용**
**- 로그인/회원가입 alert 경고 창 -> ReactToastify 적용**
**- 프로필 제안 모달 애니메이션 추가**
> feat: 회원탈퇴 시 로그아웃 상태 적용 및 모달 애니메이션 추가

- .gitignore
- src/components/common/card/Card.style.ts
- src/components/common/card/Card.tsx
- src/components/common/card/CardContainer.tsx
- src/components/common/card/elements/PositionTagContainer/PositionTagContainer.tsx
- src/components/common/card/elements/TechIconContainer/TechIconContainer.tsx
- src/components/features/Main/MainTabs/MainTabs.tsx
- src/components/features/register/ProfileProposal.tsx
- src/constants/Interests.ts
- src/constants/ParticipationMethod.ts
- src/hooks/useMainPage.ts
- src/pages/MainPage/MainPage.tsx
- src/services/index.ts
- src/services/postService.ts
- src/types/PostList.ts
- src/utils/optionUtils.ts
- 메인페이지, 카드 컴포넌트 API 데이터 연동 작업 완료 (수정사항 진행중)
- SelectOption value값 대문자로 전환
- 프로필설정 모달이동, 닫기 클릭 이벤트 추가
- gitignore에 env 파일 추가
> feat: 메인페이지, 카드 컴포넌트 API 데이터 연동 작업 완료

- src/hooks/useMainPage.ts
- src/hooks/useMyPostsPage.ts
- src/pages/MainPage/MainPage.tsx
- src/pages/MyPostPage/MyPostsPage.styles.ts
- src/pages/MyPostPage/MyPostsPage.tsx
- src/services/postService.ts
> feat: 작성글 페이지 API 데이터 연동 작업 완료

- src/components/common/card/Card.tsx
- src/hooks/useMyLikePage.ts
- src/pages/MyLikePage/MyLikePage.styles.ts
- src/pages/MyLikePage/MyLikePage.tsx
- src/services/postService.ts
- src/types/PostList.ts
> feat: 관심글 조회, 추가, 삭제 기능 작업 완료

- src/components/common/icon/BackIcon/BackIcon.tsx
- tsconfig.app.json
- stories.ts 파일 제거
- BackIcon 에러  제거
> fix: 배포 에러 수정

- src/components/common/button/Button.styles.ts
- src/components/features/Main/MainBanner/MainBanner.styles.ts
- src/css/common.css
- src/css/font.css
- src/index.css
- 본문폰트, 메인배너 폰트 변경
- 본문폰트 색상 변경
> feat: 폰트 작업

- public/Banner-Bg.svg
- src/components/features/Main/MainBanner/MainBanner.styles.ts
메인 배너 SVG 파일 vercel에서 안뜨는 이슈로 public으로 위치 이동
> fix: 메인 배너 SVG 파일 vercel에서 안뜨는 이슈로 public으로 위치 이동

- src/components/features/Chat/ChatMsg/ChatMsg.tsx
- src/components/features/Chat/ChatRoomInfoContainer/ChatRoomInfoContainer.tsx
- src/components/layout/Header/Header.tsx
- src/hooks/Chat/useChatUnread.ts
- src/hooks/Chat/useSocket.ts
- src/pages/ChatsPage/ChatsPage.tsx
- src/pages/ChatsPage/TestChat.tsx
> Feature: 신규 채팅이 온 경우 헤더에 표시되도록 알람 기능 추가

- src/components/features/login/LoginModal.styles.ts
(공통 로그인 모달) 비밀번호 입력 시 우측 아이콘 정렬 깨짐 현상 수정
> fix: 비밀번호 입력 시 우측 아이콘 정렬 깨짐 현상 수정

- src/components/common/card/Card.tsx
> feat: 관심글 버튼 클릭 시 로그인 체크

- src/components/layout/Header/Header.styles.ts
- src/pages/MainPage/MainPage.styles.ts
- src/pages/MainPage/MainPage.tsx
- 메인페이지 데이터 없을 시, 안내문구 노출
- 헤더 로고 드래그 금지 css 설정
> fix: 메인화면 수정사항 작업

- src/components/features/Main/MainBanner/MainBanner.tsx
- src/components/features/login/LoginModal.styles.ts
- src/components/features/login/LoginModal.tsx
- src/components/features/register/RegisterModal.tsx
🛠️ 노션에 작성된 것 중 사이즈 관련(아영님 해결 예정), 모달 안 로딩스피너 제외하고 수정완료했습니다.
**1. (공통) 모달 'Meetify' 로고 흐렸다가 선명해지는 애니메이션 변경 (0.5초로 빠르게 변경)**
**2. (공통) 유효하지 않는 상태로 로그인 계속 시도 하는 경우 토스트 무한정으로 뜨는 현상 수정**
**3. (공통) 모달 바깥 영역 클릭 시 모달 닫히도록 수정**
**4. (공통) 유효성 체크, DB 매칭 Toast 안내문구 수정**
**5. (등록하기 버튼)메인의 +버튼, 등록하기 버튼에서 회원가입 진입 불가능**
> Fix: login issue 해결

- src/components/features/Chat/ChatDay/ChatDay.styles.ts
- src/components/features/Chat/ChatMsg/ChatMsg.styles.ts
- src/components/features/Chat/ChatRoom/ChatRoom.styles.tsx
- src/components/layout/PostDetail/PostDetail.tsx
- src/components/layout/PostDetailMeet/PostDetailMeet.tsx
- src/css/common.css
- src/hooks/Chat/useHandleInquiry.ts
- 채팅창 전체에 패딩 추가해서여백감 추가.
- 기존 유저에게 문의하기가 있는 경우 계속 생겨나는 현상 fix.
> Fix: chat fix error

- src/components/features/login/LoginModal.tsx
- src/components/layout/PostDetail/PostDetail.tsx
- src/components/layout/PostDetailMeet/PostDetailMeet.tsx
- src/hooks/Chat/useHandleInquiry.ts
- 게시글 상세에서 문의하기 누를 시 로그인 된 상태가 아니면 로그인 모달뜨도록 변경
- 게시글 작성자와 로그인한 유저가 동일 유저일 경우 토스트 뜨도록 변경
> fix: 게시글 상세에서 문의하기 누를 시 로그인 된 상태가 아니면 로그인 모달뜨도록 변경

- src/components/common/card/Card.style.ts
> fix: 닉네임 max-width 넘을경우 숨김처리

- src/components/common/CustomSelect/CustomSelect.styles.ts
- src/components/common/ReadInput/ReadInput.styles.ts
- src/components/common/ReadTextArea/ReadTextArea.styles.ts
- src/components/common/ReadTitle/ReadTitle.styles.ts
- src/components/common/TextArea/TextArea.styles.ts
- src/components/common/input/Input.styles.ts
- src/components/features/DatePicker/DatePicker.styles.ts
- src/components/layout/PostDetail/PostDetail.styles.ts
- src/components/layout/PostDetail/PostDetail.tsx
- src/components/layout/PostDetailMeet/PostDetailMeet.styles.ts
- src/components/layout/PostDetailMeet/PostDetailMeet.tsx
- src/index.css
- src/pages/MyInfoPage/MyInfoEditPage/MyInfoEditPage.styled.ts
- src/pages/MyInfoPage/MyInfoPage/MyInfoPage.styled.ts
- src/pages/MyLikePage/MyLikePage.styles.ts
- src/pages/MyPostPage/MyPostsPage.styles.ts
- 폰트사이즈 전체적으로 통일
- 관심글/작성글 타이틀 영역 수정
> fix: 폰트사이즈 전체적으로 통일, 관심글/작성글 타이틀 영역 수정

- src/components/features/Chat/ChatMsgContainer/ChatMsgContainer.tsx
- src/components/features/Chat/ChatMsgProfile/ChatMsgProfile.styles.ts
- src/components/features/Chat/ChatMsgProfile/ChatMsgProfile.tsx
- src/components/features/Chat/ChatRoomInfo/ChatRoomInfo.styles.ts
- src/components/features/Chat/ChatRoomInfo/ChatRoomInfo.tsx
- src/components/features/Chat/ChatRoomInfoContainer/ChatRoomInfoContainer.tsx
- src/hooks/Chat/useHandleInquiry.ts
- src/pages/ChatsPage/ChatsPage.tsx
- src/store/useChatProfileStore.ts
- src/types/Chat.ts
- 신규 프로필 추가 작업 완료
- 실제 메시지를 보내기전에는 기본 프로필이 뜨는 현상이 있는데 이 부분은 일단 두겠습니다.
> feat: 신규 프로필 추가 작업 완료

- src/pages/MainPage/MainPage.tsx
- src/pages/MyLikePage/MyLikePage.tsx
- src/pages/MyPostPage/MyPostsPage.tsx
> fix: 메인, 관심글, 작성글 로딩스피너 추가

- src/pages/MyInfoPage/MyInfoEditPage/MyInfoEditPage.tsx
- 프로필 닉네임 수정 전 닉네임 고정
- 닉네임 글자수 8자까지 허용(드롭다운 모달 범위 이내)
> fix: my-info/edit 페이지 오류 수정

- src/pages/MainPage/MainPage.tsx
> fix: 메인 로딩 중복제거

- src/components/common/CustomSelect/CustomSelect.styles.ts
- src/components/common/ReadInput/ReadInput.styles.ts
- src/components/features/DatePicker/DatePicker.styles.ts
- src/components/layout/Header/Header.styles.ts
- src/components/layout/Header/Header.tsx
- src/components/layout/PostDetail/PostDetail.styles.ts
- src/components/layout/PostDetailMeet/PostDetailMeet.styles.ts
- src/components/layout/PostForm/PostForm.styles.ts
- src/components/layout/PostFormMeet/PostFormMeet.styles.ts
- src/constants/ParticipationMethod.ts
- src/pages/MainPage/MainPage.tsx
- src/pages/MyInfoPage/MyInfoEditPage/MyInfoEditPage.styled.ts
- src/pages/MyInfoPage/MyInfoPage/MyInfoPage.styled.ts
- src/pages/PostCreatePage/CreateLayout.styles.ts
- src/pages/PostPage/PostPage.styles.ts
- src/pages/PostUpdatePage/UpdateLayout.styles.ts
- 메인에서 로고 클릭 시, 새로고침
- 검색조건별 "전체" 검색 가능하도록 추가
- 기술선택 다중 선택가능 안내
- 글상세 페이지 max-width 공통변수 적용, 영역 넘치는 넓이 수정
> fix: 메인 로고 클릭 시 새로고침 & 검색조건 "전체" 추가 등

- src/App.tsx
- src/components/features/login/LoginModal.tsx
- src/components/features/register/RegisterModal.tsx
- src/pages/MyInfoPage/MyInfoEditPage/MyInfoEditPage.tsx
1. **App.tsx** ToastContainer 위치 문제
라우트 전환 시 토스트 리셋: 라우트가 변경될 때 토스트 메시지가 초기화되거나 사라질 수 있는 이슈 
-> 라우트 변경으로 인한 리렌더링이 토스트의 상태에 영향을 줄 수 있다고 합니다..!
2. MyInfoEdit 에서 무한 토스팅 이슈 해결
> Fix: toast issue 해결
